export const metadata = { title: "Terms of Service — ReplyRocket" };

export default function Terms() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16 prose prose-sm">
      <h1>Terms of Service</h1>
      <p>
        <em>Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</em>
      </p>

      <h2>1. The service</h2>
      <p>
        ReplyRocket is a Chrome extension and web dashboard that helps you draft
        replies using AI. You highlight a message, choose a tone and goal, and
        we generate three suggested drafts. You always decide what to send.
      </p>

      <h2>2. Your account</h2>
      <p>
        You&rsquo;re responsible for keeping your account secure. Don&rsquo;t share your
        login. Notify us at <a href="mailto:security@replyrocket.io">security@replyrocket.io</a> if you suspect
        unauthorized access.
      </p>

      <h2>3. Acceptable use</h2>
      <p>You agree not to use ReplyRocket to:</p>
      <ul>
        <li>Send spam, harassment, or unlawful messages.</li>
        <li>Impersonate another person.</li>
        <li>Generate content that violates Anthropic&rsquo;s usage policies.</li>
        <li>Reverse-engineer the service or scrape it.</li>
      </ul>

      <h2>4. Plans and billing</h2>
      <p>
        The Free plan includes 30 replies per month. Paid plans are billed
        monthly via Stripe and renew automatically until cancelled. You may
        cancel anytime; access continues until the end of the paid period.
      </p>

      <h2>5. AI output</h2>
      <p>
        Drafts are generated by an AI model and may contain inaccuracies. You
        are responsible for reviewing and editing every draft before sending.
        We make no warranty as to the accuracy or appropriateness of generated
        content.
      </p>

      <h2>6. Termination</h2>
      <p>
        We may suspend or terminate accounts that violate these terms. You may
        delete your account at any time from the dashboard.
      </p>

      <h2>7. Liability</h2>
      <p>
        To the maximum extent permitted by law, our total liability for any
        claim is limited to the amount you paid us in the 12 months preceding
        the claim.
      </p>

      <h2>8. Changes</h2>
      <p>
        We&rsquo;ll notify you of material changes by email. Continued use after
        changes take effect means you accept them.
      </p>

      <h2>Contact</h2>
      <p>
        <a href="mailto:hello@replyrocket.io">hello@replyrocket.io</a>
      </p>
    </main>
  );
}
